name: metasurface-ep
channels: [conda-forge, defaults]
dependencies:
  - python=3.9
  - numpy
  - scipy
  - pandas
  - h5py
  - matplotlib
  - jupyter
  - ipykernel
  - pip
  - pip:
      - black
      - ruff
      - pre-commit
